[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hylo_programs = "7wZRUBGZ2YQr1sjLPfweEyeDuuWXKXbAKR56NEcaBZ7C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"
